from django.urls import path
from . import views

app_name = 'publications'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'categories/<slug:category_slug>/editions/<slug:edition_slug>/publications/<int:post_id>/',
        views.publication_detail,
        name='publication_detail'
    ),
    path(
        'categories/<slug:category_slug>/editions/<slug:edition_slug>/',
        views.edition_detail,
        name='edition_detail'
    ),
    path(
        'categories/<slug:category_slug>/',
        views.category_detail,
        name='category_detail'
    ),
    path(
        'categories/',
        views.category_list,
        name='categories_list'
    ),
    path(
        'profile/<slug:username>/',
        views.Profile.as_view(),
        name='profile'
    ),
    path(
        'application/',
        views.article_application,
        name='application'
    ),
    path(
        'edit_publication/<int:publication_id>/',
        views.PublicationFormView.as_view(),
        name='edit_publication'
    ),
    path(
        'edir_category/<int:category_id>/',
        views.CategoryFormView.as_view(),
        name='edit_category'
    ),
    path(
        'edit_edition/<int:edition_id>/',
        views.EditionFormView.as_view(),
        name='edit_edition'
    ),
    path(
        'edit_publication/new/',
        views.PublicationFormView.as_view(),
        name='create_publication'
    ),
    path(
        'edir_category/new/',
        views.CategoryFormView.as_view(),
        name='create_category'
    ),
    path(
        'edit_edition/new/',
        views.EditionFormView.as_view(),
        name='create_edition'
    ),
    path(
        'edition_download/<int:edition_id>/',
        views.editionDowload,
        name='edition_download'
    ),
    path(
        'publication_download/<int:publication_id>/',
        views.publicationsDownload,
        name='publication_download'
    ),
    path(
        'delete_category/<int:category_id>/',
        views.deleteCategroy,
        name='delete_category'
    ),
    path(
        'delete_edition/<int:edition_id>/',
        views.deleteEdition,
        name='delete_edition'
    ),
    path(
        'delete_publication/<int:publication_id>/',
        views.deletePublication,
        name='delete_publication'
    ),
    path(
        'edit_profile/',
        views.edit_profile,
        name='edit_profile'
    ),
    path(
        'new_tag/new/',
        views.TagsCreate.as_view(),
        name='create_tag'
    ),
]
